### ISSUE TITLE
TotalEconomy not configured

### ISSUE THREAD

**Issue by hellbringer616** [strixtherealm-rpg/Strix-The-Realm#1]
Configure Total economy to use a database.
once that is complete configure in order:

- [x] mob killing

- [ ] block harvesting

- [ ] farming/fishing

**Comment by hellbringer616** [comment]
Appears to be related to MySQL8

**Comment by hellbringer616** [comment]
Investigate MySQL-Java connector driver v8

**Comment by hellbringer616** [comment]
Updated Java Connector in unstable builds, needs testing.

**Comment by SirFancyBacon** [comment]
An idea:
Within the Character Menu (from within Virtual Chest) add a placeholder to display total balance

**Comment by SirFancyBacon** [comment]
Have the balance added to the character menu, and Sponge Economy functions added to bindings.js

**Comment by SirFancyBacon** [comment]
Also scraping the idea of gaining coins from harvesting and fishing so. closing.
