### ISSUE TITLE
Itemizer based loot system

### ISSUE THREAD

**Issue by hellbringer616** [strixtherealm-rpg/Strix-The-Realm#17]
Use itemizer item pool at CustomNPC scripts to drop items on death.

Pool generated on average party level. (need to make party system)

**Comment by hellbringer616** [comment]
Either use NT-RPG party system, or CrowdBinding

**Comment by hellbringer616** [comment]
Could use Brawlator for custom Mobs.

**Comment by hellbringer616** [comment]
pushing back to 0.16; honestly it will probably be a 0.17 release.
I think 0.16 will focus on ui enhancements

**Comment by SirFancyBacon** [comment]
Itemizer 3 should allow this feature to be implemented by 0.16

**Comment by SirFancyBacon** [comment]
Feature implemented, just need content and refinement now.
