### ISSUE TITLE
Simplify character creation

### ISSUE THREAD

**Issue by hellbringer616** [strixtherealm-rpg/Strix-The-Realm#25]
Currently players must type in a series of complicated commands and GUI interactions to create players.

Simplify this to either a single command. or UI button

**Comment by hellbringer616** [comment]
*Idea1:* Use CmdBuilder (or similar plugin) to join the classes all at once with a single command.

*Idea2:*  Document step by step in /rules how to join a class (will want to remake the confirm button from a diamond to a check mark or something)

**Comment by hellbringer616** [comment]
Moving Milestone to 0.16

**Comment by SirFancyBacon** [comment]
NPC dialog using scripts is also an option

**Comment by SirFancyBacon** [comment]
Used an NPC that is in front of the player during first spawn for now, Will definitely need to be improved later.
